# Generated by Django 3.1 on 2025-04-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodedata',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='qrcodedata',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
