# Generated by Django 3.1 on 2025-04-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_reader', '0002_auto_20250429_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodedata',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
